project_id = "zkxtrwqhmjsozauzaeqh"

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.thum-screenshot]
verify_jwt = false

[functions.ai-outline]
verify_jwt = false

[functions.recommend-pages]
verify_jwt = false

[functions.gtmetrix-test]
verify_jwt = false

[functions.builtwith-lookup]
verify_jwt = false

[functions.gtmetrix-pdf]
verify_jwt = false

[functions.semrush-domain]
verify_jwt = false

[functions.pagespeed-insights]
verify_jwt = false

[functions.wappalyzer-lookup]
verify_jwt = false
