project_id = "zkxtrwqhmjsozauzaeqh"

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.thum-screenshot]
verify_jwt = false

[functions.ai-outline]
verify_jwt = false

[functions.recommend-pages]
verify_jwt = false

[functions.gtmetrix-test]
verify_jwt = false

[functions.builtwith-lookup]
verify_jwt = false

[functions.gtmetrix-pdf]
verify_jwt = false

[functions.semrush-domain]
verify_jwt = false

[functions.pagespeed-insights]
verify_jwt = false

[functions.wappalyzer-lookup]
verify_jwt = false

[functions.wave-lookup]
verify_jwt = false

[functions.observatory-scan]
verify_jwt = false

[functions.yellowlab-scan]
verify_jwt = false

[functions.deep-research]
verify_jwt = false

[functions.avoma-lookup]
verify_jwt = false

[functions.apollo-enrich]
verify_jwt = false

[functions.auto-tag-pages]
verify_jwt = false

[functions.caption-screenshots]
verify_jwt = false

[functions.apollo-team-search]
verify_jwt = false
