import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { PillarCode } from "@/data/offerings";
import type { ServiceStep } from "@/types/roadmap";

/**
 * A unified offering shape used across the roadmap editor.
 */
export interface Offering {
  id?: string;
  sku: number;
  name: string;
  defaultDuration: number;
  pillar: PillarCode;
  roadmapGrade: boolean;
  phaseOf?: number;
  phase?: number;
  billingType?: string;
  minFixed?: number | null;
  maxFixed?: number | null;
  minRetainer?: number | null;
  maxRetainer?: number | null;
  minHourly?: number | null;
  maxHourly?: number | null;
  hourlyRateExternal?: number | null;
  steps?: ServiceStep[];
}

/**
 * Phase variants are kept local — they aren't in the DB because they're
 * generated by splitting a parent offering on the timeline.
 */
const PHASE_VARIANTS: Offering[] = [
  { sku: 202, name: "Website Redesign P1", defaultDuration: 2, pillar: "FB", roadmapGrade: false, phaseOf: 201, phase: 1 },
  { sku: 203, name: "Website Redesign P2", defaultDuration: 2, pillar: "FB", roadmapGrade: false, phaseOf: 201, phase: 2 },
  { sku: 205, name: "New Website P1", defaultDuration: 2, pillar: "FB", roadmapGrade: false, phaseOf: 204, phase: 1 },
  { sku: 206, name: "New Website P2", defaultDuration: 2, pillar: "FB", roadmapGrade: false, phaseOf: 204, phase: 2 },
];

/**
 * Fetches services from the database and merges them with local phase variants.
 * Also fetches service_steps for each service and attaches them.
 * Cached via TanStack Query — service catalog rarely changes.
 */
async function fetchServiceOfferings(): Promise<Offering[]> {
  const [servicesRes, stepsRes] = await Promise.all([
    supabase
      .from("services")
      .select("id, sku, name, default_duration_months, pillar, roadmap_grade, billing_type, min_fixed, max_fixed, min_retainer, max_retainer, min_hourly, max_hourly, hourly_rate_external")
      .not("sku", "is", null)
      .order("sort_order", { ascending: true }),
    supabase
      .from("service_steps")
      .select("id, service_id, code, name, step_type, frequency, sort_order, is_onramp")
      .order("sort_order", { ascending: true }),
  ]);

  if (servicesRes.error || !servicesRes.data) return PHASE_VARIANTS;

  const stepsMap = new Map<string, ServiceStep[]>();
  if (!stepsRes.error && stepsRes.data) {
    for (const s of stepsRes.data) {
      const step: ServiceStep = {
        id: s.id,
        serviceId: s.service_id,
        code: s.code,
        name: s.name,
        stepType: s.step_type,
        frequency: s.frequency,
        sortOrder: s.sort_order,
        isOnramp: s.is_onramp,
      };
      if (!stepsMap.has(s.service_id)) stepsMap.set(s.service_id, []);
      stepsMap.get(s.service_id)!.push(step);
    }
  }

  const dbOfferings: Offering[] = servicesRes.data
    .filter((s) => s.sku != null && s.pillar != null)
    .map((s) => ({
      id: s.id,
      sku: s.sku,
      name: s.name,
      defaultDuration: s.default_duration_months ?? 1,
      pillar: s.pillar as PillarCode,
      roadmapGrade: s.roadmap_grade,
      billingType: s.billing_type,
      minFixed: s.min_fixed,
      maxFixed: s.max_fixed,
      minRetainer: s.min_retainer,
      maxRetainer: s.max_retainer,
      minHourly: s.min_hourly,
      maxHourly: s.max_hourly,
      hourlyRateExternal: s.hourly_rate_external,
      steps: stepsMap.get(s.id) || [],
    }));

  const phaseSkus = new Set(PHASE_VARIANTS.map((p) => p.sku));
  return [
    ...dbOfferings.filter((o) => !phaseSkus.has(o.sku)),
    ...PHASE_VARIANTS,
  ];
}

export function useServiceOfferings() {
  const qc = useQueryClient();
  const query = useQuery({
    queryKey: ['service-offerings'],
    queryFn: fetchServiceOfferings,
    staleTime: 30 * 60 * 1000, // services rarely change — 30 min stale
  });

  return {
    offerings: query.data ?? PHASE_VARIANTS,
    loading: query.isLoading,
    refetch: () => qc.invalidateQueries({ queryKey: ['service-offerings'] }),
  };
}
